site_name: From Rookie to Master
theme:
  name: material
  palette:
    primary: black
    scheme: slate
  repo_name: FR2M
  repo_url: https://github.com/Li-Hourong/FR2M
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs

nav:
- Start: index.md
- Data Structure & Algorithm: DS&Algorithm.md
- Computer Network: Computer Network.md
- PLP: Programming Language Principle.md
- Supplement: 
    - Verification&Encryption: Parity&Encrypto.md
    - Shell: Shell.md
    - Documents: Markdown&Latex.md
    - Sychronous&Asychronous: Sychronous&Asychronous.md
    - Git&Github: Git&Github.md