site_name: From Rookie to Master
theme:
  name: material
  palette:
    scheme: perference
    primary: black
  icon:
    repo: fontawesome/brands/git-alt
    repo_name: FR2M
    repo_url: https://github.com/Li-Hourong/FR2M
  features:
    - navigation.tabs